[versions]
brotli4jVersion = "1.20.0"

[libraries]

equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "4.2.1" }

assertj-core = { module = "org.assertj:assertj-core", version = "3.27.6" }

brotli4j-brotli4j = { module = "com.aayushatharva.brotli4j:brotli4j", version.ref = "brotli4jVersion" }
brotli4j-native-windows-amd64 = { module = "com.aayushatharva.brotli4j:native-windows-x86_64", version.ref = "brotli4jVersion" }
brotli4j-native-linux-amd64 = { module = "com.aayushatharva.brotli4j:native-linux-x86_64", version.ref = "brotli4jVersion" }
brotli4j-native-linux-aarch64 = { module = "com.aayushatharva.brotli4j:native-linux-aarch64", version.ref = "brotli4jVersion" }
brotli4j-native-osx-amd64 = { module = "com.aayushatharva.brotli4j:native-osx-x86_64", version.ref = "brotli4jVersion" }
brotli4j-native-osx-aarch64 = { module = "com.aayushatharva.brotli4j:native-osx-aarch64", version.ref = "brotli4jVersion" }

[plugins]
